schema_version = "1.0.0"

id = "blender_diffusion_texture"
name = "Diffusion Texture"
version = "1.0.1"
tagline = "A diffusion interface to generate textures in blender"
type = "add-on"

maintainer = "Eyal Benaroche <eyal.benaroche@gmail.com>"
website = "https://shaamallow.com"
tags = ["Render", "Scene"]

blender_version_min = "4.2.0"

license = ["MIT"]

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  ".*",
]
